/* main.c: the provided entry point for Project 2.
 *
 * It does almost nothing on purpose: it parses the command line into a
 * `struct container` and hands off to container_run(), which you implement in
 * container.c. All of the interesting mechanics -- the clone() and its stack,
 * the parent<->child sync pipe, the cgroup, the reaping init, the teardown --
 * live in your code. You do NOT edit this file.
 *
 *   container [--name N] [--hostname H] [--rootfs DIR] [--pids-max P]
 *             [--mem-max BYTES] [--cgroup-base DIR] -- <command> [args...]
 *
 * Everything after `--` (or the first non-option) is the command to run inside,
 * as a path within the container's root filesystem (--rootfs).
 */
#define _GNU_SOURCE
#include "container.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static long parse_bytes(const char *s)
{
    if (!strcmp(s, "max")) return -1;
    char *end;
    long v = strtol(s, &end, 10);
    switch (*end) {
    case 'k': case 'K': v *= 1024L; break;
    case 'm': case 'M': v *= 1024L * 1024; break;
    case 'g': case 'G': v *= 1024L * 1024 * 1024; break;
    }
    return v;
}

int main(int argc, char **argv)
{
    struct container c = {
        .name = "cs360v", .hostname = "container", .rootfs = "rootfs",
        .pids_max = 64, .mem_max = 64L * 1024 * 1024,
        .cgroup_base = "/sys/fs/cgroup",
        /* --net defaults (only used when --net is given) */
        .net_ifname = "ceth0", .net_ip = "10.44.0.2", .net_prefix = 24,
        .net_gw = CONTAINER_BRIDGE_GW,
    };

    int i = 1;
    for (; i < argc; i++) {
        if (!strcmp(argv[i], "--"))                     { i++; break; }
        else if (!strcmp(argv[i], "--name") && i+1<argc)      c.name = argv[++i];
        else if (!strcmp(argv[i], "--hostname") && i+1<argc)  c.hostname = argv[++i];
        else if (!strcmp(argv[i], "--rootfs") && i+1<argc)    c.rootfs = argv[++i];
        else if (!strcmp(argv[i], "--pids-max") && i+1<argc)  c.pids_max = parse_bytes(argv[++i]);
        else if (!strcmp(argv[i], "--mem-max") && i+1<argc)   c.mem_max = parse_bytes(argv[++i]);
        else if (!strcmp(argv[i], "--cgroup-base") && i+1<argc) c.cgroup_base = argv[++i];
        else if (!strcmp(argv[i], "--net"))                   c.net_enabled = 1;
        else if (!strcmp(argv[i], "--net-ip") && i+1<argc)    c.net_ip = argv[++i];
        else if (argv[i][0] == '-') { fprintf(stderr, "unknown option %s\n", argv[i]); return 2; }
        else break;
    }
    if (i >= argc) {
        fprintf(stderr, "usage: %s [opts] [--] <command> [args...]\n", argv[0]);
        return 2;
    }
    c.argv = (char *const *)&argv[i];

    return container_run(&c);
}
